In [1]:
import pandas as pd
from sklearn.impute import SimpleImputer
import numpy as np
from sklearn.preprocessing import PowerTransformer,StandardScaler
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [2]:
df=pd.read_excel('Dataset_GMSalary_outliers.xlsx')
df.head()

Id  FPYear  EDegree  GMSalary  GLArea      CMValue       CRate  PMotor  \
0   52    1982        2      6467       4  -14714.0800   25.360000  557.44   
1  113    1997        3      4707       1   -8719.0425   15.650000  518.32   
2  136    1997        2      4352       4  -10198.9120   14.800000  297.61   
3  150    1989        0      1968       4     255.7100    0.631517   64.90   
4  172    1990        2      2172       4 -165680.4240  256.200000  378.07   

   PHousehold  PHealth   PLife  PCompensations  childrennovo  
0       20.00    29.56    5.00           -9.00             1  
1        4.45    55.90    3.89           10.89             1  
2      162.80   143.36  136.47           -3.00             1  
3      197.25    29.56   18.56          451.53             1  
4       78.90   166.81    6.89           18.45             1

In [7]:
df_2=df.iloc[:,1:]
df_2.describe()

FPYear     EDegree     GMSalary      GLArea        CMValue  \
count    122.000000  122.000000   122.000000  122.000000     122.000000   
mean    2410.549180    0.639344  3114.614754    2.663934   -3064.677001   
std     4689.578326    0.803562  2035.605652    1.250525   17493.523968   
min     1974.000000    0.000000   752.000000    1.000000 -165680.424000   
25%     1980.000000    0.000000  1762.250000    1.000000    -108.930000   
50%     1986.000000    0.000000  2274.500000    3.000000     182.150000   
75%     1993.000000    1.000000  3554.750000    4.000000     549.710000   
max    53784.000000    3.000000  9131.000000    4.000000   11875.890000   

            CRate        PMotor    PHousehold       PHealth       PLife  \
count  122.000000    122.000000    122.000000    122.000000  122.000000   
mean     5.994164    401.944016    866.834836    429.362213  129.857869   
std     26.216268   1494.824169   2420.322375   2629.823445  121.967007   
min      0.008973      0.000000    -45.000000      0.000000   -6.000000   
25%      0.408948     30.395000    118.775000     69.290000   22.450000   
50%      0.791036     52.065000    331.175000    113.910000   77.125000   
75%      1.108553    122.967500    916.150000    150.722500  275.275000   
max    256.200000  11604.420000  25048.800000  28272.000000  398.300000   

       PCompensations  childrennovo  
count      122.000000    122.000000  
mean       144.631967      0.713115  
std        224.533884      0.454173  
min         -9.000000      0.000000  
25%         18.505000      0.000000  
50%         63.180000      1.000000  
75%        267.580000      1.000000  
max       1988.700000      1.000000

In [8]:
df_2=df_2.drop(112)

In [9]:
df_2.describe()

FPYear     EDegree     GMSalary      GLArea        CMValue  \
count   121.000000  121.000000   121.000000  121.000000     121.000000   
mean   1985.975207    0.628099  3086.347107    2.677686   -3092.887968   
std       7.217413    0.797206  2019.882037    1.246427   17563.475504   
min    1974.000000    0.000000   752.000000    1.000000 -165680.424000   
25%    1980.000000    0.000000  1758.000000    1.000000    -121.570000   
50%    1986.000000    0.000000  2265.000000    3.000000     173.040000   
75%    1993.000000    1.000000  3542.000000    4.000000     554.540000   
max    1998.000000    3.000000  9131.000000    4.000000   11875.890000   

            CRate        PMotor    PHousehold       PHealth       PLife  \
count  121.000000    121.000000    121.000000    121.000000  121.000000   
mean     6.040640    402.361736    873.874793    431.362149  130.745537   
std     26.320228   1501.032531   2429.131512   2640.665146  122.077784   
min      0.008973      0.000000    -45.000000      0.000000   -6.000000   
25%      0.425030     30.340000    123.350000     68.790000   22.450000   
50%      0.791840     51.230000    342.850000    113.020000   77.570000   
75%      1.121072    109.130000    917.400000    149.140000  275.720000   
max    256.200000  11604.420000  25048.800000  28272.000000  398.300000   

       PCompensations  childrennovo  
count      121.000000    121.000000  
mean       145.680331      0.719008  
std        225.167472      0.451352  
min         -9.000000      0.000000  
25%         18.670000      0.000000  
50%         65.680000      1.000000  
75%        267.830000      1.000000  
max       1988.700000      1.000000

In [10]:
df_2['EDegree'] = df_2['EDegree'].apply(lambda x: 1 if x>1 else 0)
df_2['PTotal']=df_2[['PMotor','PHousehold','PHealth','PLife','PCompensations']].sum(axis=1)


In [11]:
df_2['R_Motor'] = df_2['PMotor']/df_2['PTotal']
df_2['R_Household'] = df_2['PHousehold']/df_2['PTotal']
df_2['R_Health'] = df_2['PHealth']/df_2['PTotal']
df_2['R_Life'] = df_2['PLife']/df_2['PTotal']
df_2['R_Work_compensate'] = df_2['PCompensations']/df_2['PTotal']

In [12]:
df_train=pd.read_excel('kprototype_cluster.xlsx')


In [13]:
X=df_train.iloc[:,:-1].values
y=df_train.iloc[:,-1].values

In [14]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [15]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [16]:
from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, y_train)

KNeighborsClassifier()

In [17]:
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[4 4]
 [1 1]
 [4 4]
 ...
 [1 3]
 [2 2]
 [2 2]]


In [18]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[160  16  30   0   2]
 [ 11 350  37   0   3]
 [  6  10 782  23  26]
 [  0   1  25 509   5]
 [  0   6  30   2 506]]


0.908267716535433

In [19]:
X_out=df_2.iloc[:,:].values
X_out
X_out = sc.fit_transform(X_out)

In [20]:
y_outlier_pred = classifier.predict(X_out)
y_outlier_pred



array([3, 3, 2, 2, 3, 2, 3, 2, 3, 2, 2, 2, 3, 4, 2, 4, 2, 2, 2, 2, 2, 0,
       2, 2, 2, 2, 1, 4, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 4, 2, 2, 0, 2, 2, 2, 0, 4, 2, 4, 4, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 1, 2, 4, 2, 2, 2, 2,
       2, 2, 2, 4, 2, 2, 0, 2, 2, 2, 2, 4, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2,
       2, 2, 0, 3, 2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [21]:
df_2['labels']=y_outlier_pred

In [22]:
df_2.describe()

FPYear     EDegree     GMSalary      GLArea        CMValue  \
count   121.000000  121.000000   121.000000  121.000000     121.000000   
mean   1985.975207    0.165289  3086.347107    2.677686   -3092.887968   
std       7.217413    0.372986  2019.882037    1.246427   17563.475504   
min    1974.000000    0.000000   752.000000    1.000000 -165680.424000   
25%    1980.000000    0.000000  1758.000000    1.000000    -121.570000   
50%    1986.000000    0.000000  2265.000000    3.000000     173.040000   
75%    1993.000000    0.000000  3542.000000    4.000000     554.540000   
max    1998.000000    1.000000  9131.000000    4.000000   11875.890000   

            CRate        PMotor    PHousehold       PHealth       PLife  \
count  121.000000    121.000000    121.000000    121.000000  121.000000   
mean     6.040640    402.361736    873.874793    431.362149  130.745537   
std     26.320228   1501.032531   2429.131512   2640.665146  122.077784   
min      0.008973      0.000000    -45.000000      0.000000   -6.000000   
25%      0.425030     30.340000    123.350000     68.790000   22.450000   
50%      0.791840     51.230000    342.850000    113.020000   77.570000   
75%      1.121072    109.130000    917.400000    149.140000  275.720000   
max    256.200000  11604.420000  25048.800000  28272.000000  398.300000   

       PCompensations  childrennovo        PTotal     R_Motor  R_Household  \
count      121.000000    121.000000    121.000000  121.000000   121.000000   
mean       145.680331      0.719008   1984.024545    0.144806     0.408003   
std        225.167472      0.451352   3833.879926    0.243469     0.355722   
min         -9.000000      0.000000      9.340000    0.000000    -1.664882   
25%         18.670000      0.000000    712.360000    0.022212     0.162702   
50%         65.680000      1.000000    982.960000    0.053440     0.370598   
75%        267.830000      1.000000   1728.320000    0.112791     0.688645   
max       1988.700000      1.000000  29331.320000    0.995198     0.977887   

         R_Health      R_Life  R_Work_compensate      labels  
count  121.000000  121.000000         121.000000  121.000000  
mean     0.142741    0.153445           0.151005    2.132231  
std      0.145014    0.190991           0.201620    0.773974  
min      0.000000   -0.006063          -0.014925    0.000000  
25%      0.054336    0.015700           0.013602    2.000000  
50%      0.112047    0.066849           0.049107    2.000000  
75%      0.175386    0.266998           0.266063    2.000000  
max      0.963884    1.380086           1.284797    4.000000

In [80]:
df_2.to_excel('outliers_classification.xlsx')